// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddUserToListInput struct {
	ListID    string  `json:"listId"`
	UserEmail *string `json:"userEmail"`
	UserPhone *string `json:"userPhone"`
}

type EditItem struct {
	ID        string  `json:"id"`
	List      *string `json:"list"`
	Content   *string `json:"content"`
	Purchased *bool   `json:"purchased"`
	Recurring *bool   `json:"recurring"`
	Postponed *bool   `json:"postponed"`
}

type EditList struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Item struct {
	ID        string    `json:"id"`
	List      *List     `json:"list"`
	Content   string    `json:"content"`
	Purchased bool      `json:"purchased"`
	Recurring bool      `json:"recurring"`
	Postponed bool      `json:"postponed"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type List struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Items     []*Item   `json:"items"`
	Users     []*User   `json:"users"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NewItem struct {
	List      string `json:"list"`
	Content   string `json:"content"`
	Purchased *bool  `json:"purchased"`
	Recurring *bool  `json:"recurring"`
	Postponed *bool  `json:"postponed"`
}

type NewUser struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	AccessToken string `json:"accessToken"`
}

type RemoveUserFromListInput struct {
	ListID string `json:"listId"`
	UserID string `json:"userId"`
}

type User struct {
	ID    string  `json:"id"`
	List  []*List `json:"list"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Phone string  `json:"phone"`
	// Can be a password, pin, etc...
	AccessToken string    `json:"accessToken"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
